#!/usr/bin/env python3
"""Rebuild the kb FTS5 index and regenerate kb/INDEX.md."""

import argparse
import re
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KB = ROOT / "kb"
DB = ROOT / ".claude" / "kb.db"
SKIP = {"INDEX.md", "README.md", "TEMPLATE.md"}
KIND_ORDER = ["knowledge", "codemap", "docs", "history"]

FRONTMATTER = re.compile(r"\A---\n(.*?)\n---\n", re.S)

SCHEMA = """
DROP TABLE IF EXISTS chunks;
CREATE VIRTUAL TABLE chunks USING fts5(
    path, kind, title, tags, heading, body, line UNINDEXED,
    tokenize='porter unicode61'
);
"""


def notes():
    for path in sorted(KB.rglob("*.md")):
        if path.parent == KB and path.name in SKIP:
            continue
        yield path


def kind_of(path):
    rel = path.relative_to(KB)
    return rel.parts[0] if len(rel.parts) > 1 else "misc"


def parse_note(path):
    text = path.read_text(encoding="utf-8")
    meta, body, offset = {}, text, 0
    m = FRONTMATTER.match(text)
    if m:
        for line in m.group(1).splitlines():
            if ":" in line:
                key, value = line.split(":", 1)
                meta[key.strip()] = value.strip()
        body = text[m.end():]
        offset = text[: m.end()].count("\n")
    return meta, body, offset


def sections(body, offset, title):
    heading, current, start = title, [], offset + 1
    for i, line in enumerate(body.splitlines(), start=offset + 1):
        if line.startswith("## "):
            if any(s.strip() for s in current):
                yield heading, "\n".join(current).strip(), start
            heading, current, start = line[3:].strip(), [], i
        else:
            current.append(line)
    if any(s.strip() for s in current):
        yield heading, "\n".join(current).strip(), start


def newest_source():
    times = [p.stat().st_mtime for p in notes()]
    return max(times) if times else 0.0


def build():
    DB.parent.mkdir(parents=True, exist_ok=True)
    con = sqlite3.connect(DB)
    con.executescript(SCHEMA)
    catalog, rows = [], []
    for path in notes():
        meta, body, offset = parse_note(path)
        rel = str(path.relative_to(ROOT))
        title = meta.get("title") or path.stem.replace("-", " ")
        tags = meta.get("tags", "").strip("[] ")
        kind = kind_of(path)
        catalog.append(
            {
                "path": rel,
                "kind": kind,
                "title": title,
                "summary": meta.get("summary", ""),
            }
        )
        for heading, text, line in sections(body, offset, title):
            rows.append((rel, kind, title, tags, heading, text, line))
    con.executemany("INSERT INTO chunks VALUES (?,?,?,?,?,?,?)", rows)
    con.commit()
    con.close()
    return catalog, len(rows)


def write_index(catalog):
    lines = [
        "# KB index",
        "",
        "Generated by `scripts/kb_index.py` — do not edit by hand.",
        "",
    ]
    kinds = sorted(
        {n["kind"] for n in catalog},
        key=lambda k: (KIND_ORDER.index(k) if k in KIND_ORDER else 99, k),
    )
    for kind in kinds:
        lines += [f"## {kind}", ""]
        for note in sorted(
            (n for n in catalog if n["kind"] == kind), key=lambda n: n["path"]
        ):
            target = Path(note["path"]).relative_to("kb")
            hook = note["summary"] or note["title"]
            lines.append(f"- [{note['title']}]({target}) — {hook}")
        lines.append("")
    if not catalog:
        lines += ["_No notes yet._", ""]
    (KB / "INDEX.md").write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--if-stale", action="store_true", help="skip when index is current")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    if not KB.exists():
        return 0
    if args.if_stale and DB.exists() and DB.stat().st_mtime >= newest_source():
        return 0

    catalog, count = build()
    write_index(catalog)
    if not args.quiet:
        print(f"indexed {len(catalog)} notes / {count} sections -> {DB.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
